export { createAuthenticationSaga } from './Domain/Saga/Flow';
export { createLogin, Login } from './Domain/Command/Login';
export { createLogout, Logout } from './Domain/Command/Logout';
export { createInitializeCurrentUser, InitializeCurrentUser } from './Domain/Command/InitializeCurrentUser';
export { UserLoginWasCancelled } from './Domain/Event/UserLoginWasCancelled';
export { UserWasLoggedOut } from './Domain/Event/UserWasLoggedOut';
export { UserAuthenticationWasRefreshed } from './Domain/Event/UserAuthenticationWasRefreshed';
export { UserAuthenticationRefreshFailed } from './Domain/Event/UserAuthenticationRefreshFailed';
export { UserAuthenticationRefreshWasRequested } from './Domain/Event/UserAuthenticationRefreshWasRequested';
export { UserLoginFailed } from './Domain/Event/UserLoginFailed';
export { UserLoginWasNotExecuted } from './Domain/Event/UserLoginWasNotExecuted';
export { UserLoginWasRequested } from './Domain/Event/UserLoginWasRequested';
export { UserLogoutWasNotExecuted } from './Domain/Event/UserLogoutWasNotExecuted';
export { UserWasLoggedIn } from './Domain/Event/UserWasLoggedIn';
export { findCurrentAuthUser } from './Domain/Query/CurrentAuthUserQuery';
export { authenticationReducer } from './Domain/Reducer';
export * from './Domain/Types';
export {createLoginErrorResult} from "Packages/Common/Authentication/Domain/Saga/CustomEffect/Login";
export {LoginResult} from "Packages/Common/Authentication/Domain/Saga/CustomEffect/Login";
export {LoginErrorResult} from "Packages/Common/Authentication/Domain/Saga/CustomEffect/Login";
export {LoginSuccessResult} from "Packages/Common/Authentication/Domain/Saga/CustomEffect/Login";
export const authTokenCookieName = 'authUser';
export const authTokenCookieTimeToLiveInDays = 14;
export const authRefreshBeforeExpirationInSeconds = 60;